### ISSUE TITLE
Redux version

### ISSUE THREAD

**Issue by sassanh** [lemanse/simple-react-app#5]
Thanks for this helpful sample, could you please provide a redux version of this too? I wasn't able to make redux+router work with livereactload.

**Comment by tukkajukka** [comment]
Hi @sassanh and thanks for the comment! Redux version is the next thing on my to-do list, let's see how it turns out. What kind of problems did you encounter?

**Comment by sassanh** [comment]
@tukkajukka Thanks for following this up. The problems and the solutions are discussed in details here https://github.com/milankinen/livereactload/issues/64
and here https://github.com/milankinen/livereactload/issues/43
Fortunately I were able to make it work. I think it'll be helpful for newcomers if you provide the full example in this repo.
